Homework2
AndriiBoichuk/8ball pull request #12
Opened 2021-11-09 08:09 UTC by AndriiBoichuk

Удалил логику DB c ViewController, сделал протокол ManagedObjectConvertible для DB Services.
Структурировал код в соответствии со SOLID.
Использовал Constructor Injection for API services

2021-11-09 19:52 UTC, ios-school-yalantis requested changes

2021-11-09 19:52 UTC, ios-school-yalantis commented on 8-ball/Controllers/AnswersTableViewController.swift
> +}
работу с контекстом нужно вынести в отдельный класс

2021-11-09 19:52 UTC, ios-school-yalantis commented on 8-ball/Controllers/ViewController.swift
> +}
тоже работа с контекстом

2021-11-09 20:34 UTC, AndriiBoichuk reviewed
Логика database вынесена в отдельный класс

2021-11-09 20:58 UTC, ios-school-yalantis commented
нужно вынести создание зависимостей из классов которые их используют

2021-11-09 21:58 UTC, AndriiBoichuk commented
> нужно вынести создание зависимостей из классов которые их используют

Спасибо, уже исправил

2021-11-10 17:47 UTC, ios-school-yalantis approved these changes
незначительные замечания, после исправления можно мержить

2021-11-10 17:47 UTC, ios-school-yalantis commented on 8-ball/Controllers/SettingsViewController.swift
> +//    }
закоментированый код нужно удалить

2021-11-10 17:47 UTC, ios-school-yalantis commented on 8-ball/Models/DBManager.swift
> +    var delegate: AnswersTableViewController?
delegate должен быть weak

2021-11-10 17:47 UTC, ios-school-yalantis commented on 8-ball/Models/DBService.swift
> +
лишняя пустая строка или убрать или добавить пустую в начало протокола

2021-11-10 18:18 UTC, AndriiBoichuk commented
> незначительные замечания, после исправления можно мержить

Спасибо, исправил!

2021-11-10 18:18 UTC, merged