Hometask3
AndriiBoichuk/8ball pull request #13
Opened 2021-11-10 20:18 UTC by AndriiBoichuk

2021-11-12 11:31 UTC, seropusha requested changes
В принципе все в поряке
нужно избавится от ворнингов, не все строки перенесены в Localizable.strings. Swiftlint, SwiftGen подключены корректно.

2021-11-12 11:31 UTC, seropusha commented on 8-ball/SupportingFiles/Reachability.swift
>          }) else {
Нужно добавить исключений для линтеровшика в Reachability.swift (swiftlint:disable)
Так как это не твой код и уверен что он работает, можно его не подсвечивать ворнингами. 

Либо сделать рефакторинг что бы не было ворнингов.

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Controllers/AnswersTableViewController.swift
>  class AnswersTableViewController: UITableViewController {
Есть ворнинги в этом файле от линтера.

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Controllers/ViewController.swift
>  class ViewController: UIViewController {
Стоит переименовать этот контроллер как-то по конкретнее, из-за того что он называется `ViewController` его сложно найти среди остальных вью контроллеров.

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Controllers/ViewController.swift
>      }
Обратил внимание что на 69 строчке есть ворнинг

в компютед прочерти которое только возвращает значение указывать `get {}` не нужно

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Controllers/ViewController.swift
>              }
не все строки добавлены в Localizable

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Models/AnswerManager.swift
> +    weak var delegate: ViewController?
для общения с делегатом лучше использовать протокол

2021-11-12 11:31 UTC, seropusha commented on 8-ball/Base.lproj/Localizable.strings
> +"canceled" = "Motion cancelled";
лучше называть сразу как то конкретнее

"shake.title" || "canceled.error.title"

так же можно называть строки через андерскор "shake_title" но я больше склоняюсь к первому варианту потому что их будет легче искать в коде.

2021-11-12 16:43 UTC, AndriiBoichuk commented
> В принципе все в поряке
> 
> * нужно избавится от ворнингов
> * не все строки перенесены в Localizable.strings.
> * лучше создать папку  `Resource` и переместить в нее все ресурсы(Localizable.string, Assets) вместе с SwiftGen папкой что бы все лежало в одном месте
>   Swiftlint, SwiftGen подключены корректно.

Спасибо за развернутый фидбек, уже исправил указанные ошибки.

2021-11-15 16:02 UTC, seropusha commented on 8-ball/Controllers/AnswersTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: L10n.Cell.identifier, for: indexPath)
Identifier не обязательно в строки выносить) но ничего страшного

2021-11-15 16:03 UTC, seropusha commented on 8-ball/Controllers/AnswersTableViewController.swift
> +        let sortDescriptor = NSSortDescriptor(key: L10n.Key.answer, ascending: true)
тоже не обязательно выносить в строки так как это название поля и оно может поменяться
можно использовать #keyPath(Item.propertyName)

2021-11-15 16:05 UTC, seropusha reviewed
в общем все хорошо, можешь мертвить

2021-11-15 16:05 UTC, seropusha approved these changes

2021-11-15 16:06 UTC, merged