Made Tabbar, saving responses from API to device memory
AndriiBoichuk/8ball pull request #17
Opened 2021-11-26 09:48 UTC by AndriiBoichuk

2021-11-28 13:42 UTC, ios-school-yalantis requested changes
Есть вопросы по поводу DBManager:
- инкапсулировать в нем storeContainer и contexts
- при сохранении обязательно нужно у контекста узнать есть ли в нем изменения context.hasChanges потому только вызывать save()
- можно добавить private func которая будет заниматься фетчингом любых моделей
```
  private func fetchObjects<T: NSManagedObject>(
        _ request: NSFetchRequest<T>,
        completion: @escaping (Result<[T]>) -> Void
    ) {
        let context = yourContext
        context.perform {
            do {
                let result = try context.fetch(request) as! [T]
                completion(.success(result))
            } catch let error {
                completion(.failure(error))
            }
```
и в публичных уже формировать реквест и возвращать данные 

- AnswersViewModel создает реквест, он должен создаваться внутри DBService с нужными параметрами, и этот код должен быть в модели!

- SettingsViewController && MainViewController много строк которые нужно добавить в Localizable
- так же нужно удалить закоменченный код!
-

2021-11-28 13:42 UTC, ios-school-yalantis commented on 8-ball/Flows/MainTabBarController.swift
> +    private let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
UIAppDelegate && UISceneDelegate нужно использовать только для получения ивентов от системы!
Принцип единой отвецвенности

нужно убрать из них весь код который там не должен находится, такой как:
- persistentContainer - перенести его в DBService и инкапсулировать все там
- saveContext() вызывай через UIApplication.notification через NotificationCenter внутри DBService
- Reachability не должен там находится
-

2021-11-28 13:42 UTC, ios-school-yalantis commented on 8-ball/Flows/MainTabBarController.swift
> +        return DBManager(context: context)
в кейсе когда внутри DBService будет инкапсулированы context && StoreContainer для каждого инстанса DBService они буду свои, это ведет к тому что, все модели контроллеров должны быть созданы с одним и тем же инстансом DBService.

Иначе может быть кейс когда добавишь объекты в одном контексте, и сохранишь на другом экране (совсем в другом контексте) и объекты не добавятся в стор. Что бы этого избежать нужно юзать 1 инстанс DBService.

и не делай его синглтоном, просто создай его внутри модели таббакра и прокинь во все модели контроллеров.

2021-11-29 20:29 UTC, AndriiBoichuk commented on 8-ball/Flows/MainTabBarController.swift
> +    private let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
Спасибо за развернутый фидбек. 
Исправил все замечания. Остался только вопрос, куда перенести Reachability из AppDelegate. Возможно, также через `Notification Center` сделать?

2021-11-30 09:24 UTC, ios-school-yalantis commented on 8-ball/Flows/MainTabBarController.swift
> +    private let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
В отдельный файл или в ConnectionManager как private class. по проекту использовать ConnectionManager, а Reachability будет использоваться только в ConnectionManager.

2021-11-30 09:31 UTC, ios-school-yalantis approved these changes
Мелкие комменты
Можно мерджить.

2021-11-30 09:31 UTC, ios-school-yalantis commented on 8-ball/Managers/DBManager.swift
> +    private lazy var context: NSManagedObjectContext = {
лучше это все инициализировать в init() так лучше читается код 
не критично

2021-11-30 09:48 UTC, merged